#!/bin/bash

HASH="%C(yellow)%h%C(reset)"
RELATIVE_TIME="%C(green)(%ar)%C(reset)"
AUTHOR="%C(bold blue)%an%C(reset)"
REFS="%C(red)%d%C(reset)"
SUBJECT="%s%C(reset)"

FORMAT="$HASH{$RELATIVE_TIME{$AUTHOR{$REFS $SUBJECT"

function pretty_git_log() {
  git log --graph --pretty="tformat:$FORMAT" $* |

      # replace 2 years ago with 2 years
      sed -Ee 's/(^[^<]*) ago)/\1)/' |

      # replace (2 years, 5 months) with (2 years)
      sed -Ee 's/(^[^<]*), [[:digit:]]+ .*months?)/\1)/' |

      # line columns up based on { delimeter
      column -t -s '{' |

      # page only if we need to
      less -FXRS
}
