#!/usr/bin/ruby

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end

# IRB.conf[:IRB_RC] = Proc.new do
#   ActiveRecord::Base.logger = Logger.new(STDOUT)
#   ActiveRecord::Base.instance_eval { alias :[] :find }
# end
