#!/usr/bin/env ruby
# vim: ft=ruby

git_bundles = %w[
  Lokaltog/vim-powerline.git
  Townk/vim-autoclose.git
  airblade/vim-gitgutter
  chriskempson/vim-tomorrow-theme.git
  dtyuan/vim-rspec.git
  groenewege/vim-less.git
  haraldmartin/vim-snipmate.git
  henrik/vim-ruby-runner.git
  kchmck/vim-coffee-script.git
  kien/ctrlp.vim
  mileszs/ack.vim.git
  othree/html5-syntax.vim.git
  scrooloose/snipmate-snippets.git
  sjl/vitality.vim.git
  tpope/vim-bundler.git
  tpope/vim-dispatch
  tpope/vim-fugitive.git
  tpope/vim-git.git
  tpope/vim-haml.git
  tpope/vim-markdown.git
  tpope/vim-ragtag.git
  tpope/vim-rails.git
  tpope/vim-surround.git
  tpope/vim-unimpaired.git
  vim-ruby/vim-ruby
  vim-scripts/Align.git
  vim-scripts/Arduino-syntax-file.git
  vim-scripts/ColorX.git
  vim-scripts/Gist.vim.git
  vim-scripts/JavaScript-Indent.git
  vim-scripts/camelcasemotion.git
  vim-scripts/endwise.vim.git
  vim-scripts/tComment.git
  altercation/vim-colors-solarized
]

require 'fileutils'

bundle_dir = File.expand_path('../bundle/', __FILE__)

# Find unlisted bundles (bundles not on disk will the script checkout)
bundles_listed   = git_bundles.map { |url| url.split('/').last.sub('.git', '')}.map &:downcase
bundles_on_disk  = Dir["#{bundle_dir}/*"].map { |path| File.basename(path) }.map &:downcase
bundles_unlisted = bundles_on_disk - bundles_listed

if bundles_unlisted.any?
  puts 
  puts "*** Some bundles found on disk but not on file ***"
  bundles_unlisted.each do |bundle|
    url = File.read("#{bundle_dir}/#{bundle}/.git/config").match(/url = (.+)$/)[1]
    puts "#{bundle} (#{url})"
  end
  puts
end

git_bundles.each do |url|
  dirname = File.basename(url).sub(/\.git$/, '')
  puts "* Unpacking #{url} into #{dirname}"
  dir = File.join(bundle_dir, dirname)
  `cd #{dir} 2>/dev/null && git pull || git clone https://github.com/#{url} #{dir}`
end

puts "* Updating to latest pathogen"
autoload_dir = File.expand_path('../autoload', __FILE__)
`curl -s --location http://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim > #{autoload_dir}/pathogen.vim`
