#!/usr/bin/env ruby
# vim: ft=ruby

# from: http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen
git_bundles = %w[
  chriskempson/vim-tomorrow-theme.git
  Townk/vim-autoclose.git
  dtyuan/vim-rspec.git
  haraldmartin/vim-snipmate.git
  henrik/vim-ruby-runner.git
  kchmck/vim-coffee-script.git
  mileszs/ack.vim.git
  othree/html5-syntax.vim.git
  scrooloose/snipmate-snippets.git
  tpope/vim-bundler.git
  tpope/vim-bundler.git
  tpope/vim-fugitive.git
  tpope/vim-git.git
  tpope/vim-haml.git
  tpope/vim-markdown.git
  tpope/vim-ragtag.git
  tpope/vim-rails.git
  tpope/vim-surround.git
  tpope/vim-unimpaired.git
  vim-scripts/Align.git
  vim-scripts/Arduino-syntax-file.git
  vim-scripts/ColorX.git
  vim-scripts/Command-T.git
  vim-scripts/Gist.vim.git
  vim-scripts/JavaScript-Indent.git
  vim-scripts/camelcasemotion.git
  vim-scripts/endwise.vim.git
  vim-scripts/tComment.git
]

# https://github.com/tclem/vim-arduino.git
# git://github.com/altercation/vim-colors-solarized.git
# git://github.com/vim-scripts/Color-Sampler-Pack.git
# https://github.com/tpope/vim-speeddating.git
# git://github.com/flazz/vim-colorschemes.git


require 'fileutils'

bundle_dir = File.expand_path('../bundle/', __FILE__)

# Found unlisted bundles (bundles not on disk will the script checkout)
bundles_listed = git_bundles.map { |url| url.split('/').last.sub('.git', '')}
bundles_on_disk = Dir["#{bundle_dir}/*"].map { |path| File.basename(path) }
bundles_unlisted = bundles_on_disk - bundles_listed

if bundles_unlisted.any?
  puts 
  puts "*** Some bundles found on disk but not on file ***"
  bundles_unlisted.each do |bundle|
    url = File.read("#{bundle_dir}/#{bundle}/.git/config").match(/url = (.+)$/)[1]
    puts "#{bundle} (#{url})"
  end
  puts
end

git_bundles.each do |url|
  dirname = File.basename(url).sub(/\.git$/, '')
  puts "* Unpacking #{url} into #{dirname}"
  dir = File.join(bundle_dir, dirname)
  `cd #{dir} 2>/dev/null && git pull || git clone https://github.com/#{url} #{dir}`
end

puts "* Updating to latest pathogen"
autoload_dir = File.expand_path('../autoload', __FILE__)
`curl -s --location http://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim > #{autoload_dir}/pathogen.vim`
