#!/usr/bin/env ruby
# vim: ft=ruby

# from: http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = %w[
  http://github.com/airblade/vim-rooter.git
  http://github.com/mileszs/ack.vim.git
  http://github.com/reinh/vim-makegreen.git
  http://github.com/skammer/vim-css-color.git
  http://github.com/taxilian/nerdtree.git
  http://github.com/tpope/vim-fugitive.git
  http://github.com/tpope/vim-git.git
  http://github.com/tpope/vim-haml.git
  http://github.com/tpope/vim-markdown.git
  http://github.com/tpope/vim-ragtag.git
  http://github.com/tpope/vim-rails.git
  http://github.com/tpope/vim-speeddating.git
  http://github.com/tpope/vim-surround.git
  http://github.com/tpope/vim-unimpaired.git
  http://github.com/vim-scripts/ColorX.git
  http://github.com/vim-scripts/Command-T.git
  http://github.com/vim-scripts/Gist.vim.git
  http://github.com/vim-scripts/camelcasemotion.git
  http://github.com/vim-scripts/endwise.vim.git
  http://github.com/vim-scripts/hexHighlight.vim.git
  http://github.com/vim-scripts/tComment.git
  http://github.com/vim-scripts/Align.git
]

require 'fileutils'

bundle_dir = File.expand_path('../bundle/', __FILE__)

git_bundles.each do |url|
  dirname = File.basename(url)
  puts "* Unpacking #{url} into #{dirname}"
  dir = File.join(bundle_dir, dirname)
  `cd #{dir} 2>/dev/null && git pull || git clone #{url} #{dir}`
end

puts "* Updating to latest pathogen"
autoload_dir = File.expand_path('../autoload', __FILE__)
`curl -s http://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim > #{autoload_dir}/pathogen.vim`
