#!/usr/bin/env ruby

class RailsProjectCompletion
  def initialize(command)
    @command = command
  end
  
  def matches
    projects.select do |task|
      #task[0, typed.length].downcase == typed.downcase
      task.sub('/Users/martin/Projects/', '')[0, typed.length].downcase == typed.downcase
    end
  end
  
  def typed
    @command[/\s(.+?)$/, 1] || ''
  end
  
  def projects
    passenger_projects # + apacherb_projects
  end
  
  def passenger_projects
    find_document_roots('passenger_pane_vhosts')
  end
  
  def apacherb_projects
    find_document_roots('apacherb_vhosts')
  end
  
  def find_document_roots(folder)
    `for file in /etc/apache2/#{folder}/*.conf; do grep DocumentRoot $file | awk '{print $2}' | sed 's/\"//g' | sed 's/\\/public$//g' ; done`.split("\n")
  end
end

puts RailsProjectCompletion.new(ENV["COMP_LINE"]).matches
exit 0
